[PRMT-1041] Link up canary webhook with list of dependencies that can be updated

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -48,6 +48,16 @@ function configure_aws_service_auth_keys {
     export AUTHORIZATION_KEYS=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region ${AWS_DEFAULT_REGION} --name  ${parameter_name} | jq -r .Parameter.Value")
 }
 
+function get_aws_ssm_secret {
+  secret_id=$1
+  json=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id")
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
 #######################
 # Terraform Functions #
 #######################
@@ -77,6 +87,22 @@ function tf_apply {
   terraform get # modules
   terraform apply nhs_deployment.tfplan
   terraform output -json > tf-out.json
+}
+
+####################
+# Script Functions #
+####################
+
+function send_canary_message {
+  node scripts/send-canary-message.js $(npm outdated --parseable)
+}
+
+function configure_hangout_webhook {
+  export GOOGLE_CHAT_CANARY_WEBHOOK=$(get_aws_ssm_secret "/NHS/GoCD/prod/google-chat-canary-webhook")
+  if [ -z "${GOOGLE_CHAT_CANARY_WEBHOOK}" ]; then
+    echo "Unable to obtain GOOGLE_CHAT_CANARY_WEBHOOK from AWS"
+    exit 5
+  fi
 }
 
 ############################
@@ -122,9 +148,10 @@ case "${command}" in
       ;;
   _list_outdated)
       npm install
-      npm outdated > outdated-dependencies.txt || exit 0
+      npm outdated > outdated-dependencies.txt || send_canary_message
       ;;
   list_outdated)
+      configure_hangout_webhook
       dojo "./tasks _list_outdated"
       ;;
   update_package_json)
